export const UserActionTypes  = {
    SET_CURRENT_USER:  'SET_CURRENT_USER',
    GOOGLE_SIGNiN_START: 'GOOGLE_SIGNiN_START',
    GOOGLE_SIGNiN_SUCCESS: 'GOOGLE_SIGNiN_SUCCESS',
    GOOGLE_SIGNiN_FAILURE: 'GOOGLE_SIGNiN_FAILURE',
    EMAIL_SIGNiN_START: 'EMAIL_SIGNiN_START',
    EMAIL_SIGNiN_SUCCESS: 'EMAIL_SIGNiN_SUCCESS',
    EMAIL_SIGNiN_FAILURE: 'EMAIL_SIGNiN_FAILURE',
    SIGNNOUT_SIGNiN_START: 'SIGNNOUT_SIGNiN_START',
    SIGNNOUTL_SIGNiN_SUCCESS: 'SIGNNOUT_SIGNiN_SUCCESS',
    SIGNNOUT_SIGNiN_FAILURE: 'SIGNNOUT_SIGNiN_FAILURE',
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    

}